exports.helpWords = {'#help': true,
					 '#Help': true,
					 '#HElP': true,
					 '#HELp': true,
					 '#HELP': true,
					 '#hELP': true,
					 '#heLP': true,
					 '#helP': true,
					 'help': true,
					 'Help': true,
					 'HElP': true,
					 'HELp': true,
					 'HELP': true,
					 'hELP': true,
					 'heLP': true,
					 'helP': true,
					 'help': true,
					 'help me': true,
					 'Help Me': true,
					 'HELP ME': true,
					 '#help me': true,
					 '#Help Me': true,
					 '#HELP ME': true,
					 '#help menu': true,
					 '#Help menu': true
					}